const themeLight = {
  dark: false,
  "colors": {
    "primary": "rgb(94, 143, 135)",
    "onPrimary": "#FFFFFF",
    "primaryContainer": "#506F68",
    "onPrimaryContainer": "#FFFFFF",
    "secondary": "#72999C",
    "onSecondary": "#FFFFFF",
    "secondaryContainer": "#4E6A6E",
    "onSecondaryContainer": "#FFFFFF",
    "tertiary": "#8CA1A5",
    "onTertiary": "#FFFFFF",
    "tertiaryContainer": "#6B8085",
    "onTertiaryContainer": "#FFFFFF",
    "error": "#FF5252",
    "onError": "#FFFFFF",
    "errorContainer": "#BD3B3B",
    "onErrorContainer": "#FFFFFF",
    "background": "#121212",
    "onBackground": "#FFFFFF",
    "surface": "#1E1E1E",
    "onSurface": "#FFFFFF",
    "surfaceVariant": "#272727",
    "onSurfaceVariant": "#FFFFFF",
    "outline": "#FFFFFF",
    "outlineVariant": "#A0A0A0",
    "shadow": "rgba(0, 0, 0, 0.2)",
    "scrim": "rgba(0, 0, 0, 0.5)",
    "inverseSurface": "#FFFFFF",
    "inverseOnSurface": "#000000",
    "inversePrimary": "#FFFFFF",
    "elevation": {
      "level0": "transparent",
      "level1": "rgba(0, 0, 0, 0.05)",
      "level2": "rgba(0, 0, 0, 0.1)",
      "level3": "rgba(0, 0, 0, 0.15)",
      "level4": "rgba(0, 0, 0, 0.2)",
      "level5": "rgba(0, 0, 0, 0.25)"
    },
    "surfaceDisabled": "rgba(255, 255, 255, 0.12)",
    "onSurfaceDisabled": "rgba(255, 255, 255, 0.38)",
    "backdrop": "rgba(0, 0, 0, 0.5)"
  },
};

const themeDark = {
  dark: true,
  colors: {
    primary: "rgb(94, 143, 135)",
    onPrimary: "#FFFFFF",
    primaryContainer: "#506F68",
    onPrimaryContainer: "#FFFFFF",
    secondary: "#72999C",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#4E6A6E",
    onSecondaryContainer: "#FFFFFF",
    tertiary: "#8CA1A5",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#6B8085",
    onTertiaryContainer: "#FFFFFF",
    error: "#FF5252",
    onError: "#FFFFFF",
    errorContainer: "#BD3B3B",
    onErrorContainer: "#FFFFFF",
    background: "#121212",
    onBackground: "#FFFFFF",
    surface: "#1E1E1E",
    onSurface: "#FFFFFF",
    surfaceVariant: "#272727",
    onSurfaceVariant: "#FFFFFF",
    outline: "#FFFFFF",
    outlineVariant: "#A0A0A0",
    shadow: "rgba(0, 0, 0, 0.2)",
    scrim: "rgba(0, 0, 0, 0.5)",
    inverseSurface: "#FFFFFF",
    inverseOnSurface: "#000000",
    inversePrimary: "#FFFFFF",
    elevation: {
      level0: "transparent",
      level1: "rgba(0, 0, 0, 0.05)",
      level2: "rgba(0, 0, 0, 0.1)",
      level3: "rgba(0, 0, 0, 0.15)",
      level4: "rgba(0, 0, 0, 0.2)",
      level5: "rgba(0, 0, 0, 0.25)"
    },
    surfaceDisabled: "rgba(255, 255, 255, 0.12)",
    onSurfaceDisabled: "rgba(255, 255, 255, 0.38)",
    backdrop: "rgba(0, 0, 0, 0.5)"
  },
};

const themes = {
  light: themeLight,
  dark: themeDark,
};

export default themes;
